version: '3'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: easyopen-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: tenyon # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - easynetwork # 指定网络
  redis:
    image: redis:7.2.5
    container_name: easyopen-redis
    ports:
      - "6379:6379"
    networks:
      - easynetwork
    volumes:
      - ./.redis-data:/data # 持久化
#  rabbitmq:
#    image: rabbitmq:3.12.6-management # 支持管理面板的消息队列
#    container_name: yuoj-rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672" # RabbitMQ Dashboard 端口
#    volumes:
#      - ./.rabbitmq-data:/var/lib/rabbitmq # 持久化
#    networks:
#      - easynetwork
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: easyopen-nacos
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - easynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
networks:
  easynetwork:
