spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
    session:
      cookie:
        max-age: 2592000
        path: "/api"
wx:
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  open:
    appId: xxx
    appSecret: xxx