spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
    session:
      cookie:
        max-age: 2592000
        path: "/api"
wx:
  mp:
    configs:
      - appId: ${wechat.mp.configs.appId}
        secret-key: ${wechat.mp.configs.secretKey}
        token: ${wechat.mp.configs.token}
    callback: ${wechat.mp.callback}
