spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 2592000
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/app
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: "/api"