server:
  port: 8101
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
    gateway:
      routes:
        - id: easy-open-user-service
          uri: lb://easy-open-user-service
          predicates:
            - Path=/api/user/**
        - id: easy-open-api-service
          uri: lb://easy-open-api-service
          predicates:
            - Path=/api/interfaceInfo/**
        - id: easy-open-app-service
          uri: lb://easy-open-app-service
          predicates:
            - Path=/api/app/**
  main:
    web-application-type: reactive
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: swagger2